### ISSUE TITLE
Error: soap:Server>result returns more than one elements

### ISSUE THREAD

**Issue by Marc-Petersen** [scandihealth/lpr3-docs#295]
When submitting a FE for a patient, we received the following error, encoded in BASE64:

_1.021ep1http://schemas.xmlsoap.org/soap/envelope/2ep2urn:epic-com:Interconnect.2011.Services11:Envelope21:Header31:Body41:Fault5faultcode6faultstring72:MessageProperties82:HTTPHeaders92:X-OneAgent-JS-Injection102:Strict-Transport-Security112:Transfer-Encoding122:Connection132:Content-Type142:Date152:Set-Cookie162:StatusCode172:StatusCodeNumber182:StatusDescription192:ContentType202:MediaType12345Asoap:Server6Aresult returns more than one elements789Atrue10Amax-age=31536000; includeSubDomains11Achunked12Aclose13Amultipart/related; type="application/xop+xml"; boundary="uuid:bb0874da-7eb4-4989-bde6-513cf9ef4f64"; start="<root.message@cxf.apache.org>"; start-info="text/xml"14ATue, 29 Jan 2019 09:03:52 GMT15AdtCookie=1$E5709CC7632E7F04591DDFD932890DA8; Path=/; Domain=.dsdn.dk16AInternalServerError17A50018AInternal Server Error19Amultipart/related; type="application/xop+xml"20Amultipart/related_

We're not sure what this error means, or if it is logged in by fault.

**Comment by TueCN** [comment]
Yes this is one of the reasons we are doing away with the current "relation registration" check. 

This error happens when the same custodian (CVR) is registered as having a relation to multiple authors (SOR units).
There is not much you can do about it right now, but the fix is in progress and the forecast is "soon".

**Comment by Marc-Petersen** [comment]
Any news on this issue? We're currently not logging this specific error, so it might have been resolved?

**Comment by TueCN** [comment]
The underlying issue is still not resolved, but I believe SDS might have mitigated the issue by instructing reporting authorities to, for each CVR-number, always use the same SOR-id in CDA custodian/author.

We (DXC and SDS) are still iterating on a general resolution of how CVR/SOR codes should be linked and checked by the service.

**Comment by smunck** [comment]
SDS has (some time ago) resolved errors in the whitelisning of the four privately owned institutions. The submissions should work now.
