### ISSUE TITLE
Cannot delete Encounter

### ISSUE THREAD

**Issue by JacobBangSSE** [scandihealth/lpr3-docs#84]
We have successfully created an Episode of Care and added an Encounter. But when we try delete the Encounter it looks like the Encounter is deleted but when we are checking "https://lpradm-test.sds.dsdn.dk/gui-client" the Encounter is still there and if we try delete the same Encounter twice it looks like the Encounter is deleted successfully both times.

The return value from PatientHealthcareReportingService is (kind of strange we are getting business rules warnings for the Encounter we are trying to delete):
```xml
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
   <soap:Header>
      <ns10:Header xmlns="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:ns10="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd" xmlns:ns11="http://www.nsi.dk/hsuid/2016/08/hsuid-1.1.xsd" xmlns:ns2="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" xmlns:ns3="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0" xmlns:ns4="urn:ihe:iti:xds-b:2007" xmlns:ns5="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns:ns6="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:ns7="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns8="http://www.w3.org/2000/09/xmldsig#" xmlns:ns9="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
         <ns10:SecurityLevel>3</ns10:SecurityLevel>
         <ns10:Linking>
            <ns10:MessageID>b3d06026c0a8380100c79bd58c78de2c</ns10:MessageID>
         </ns10:Linking>
         <ns10:FlowStatus>flow_finalized_succesfully</ns10:FlowStatus>
      </ns10:Header>
   </soap:Header>
   <soap:Body>
      <ns2:RegistryResponse status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Success" xmlns="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:ns10="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd" xmlns:ns11="http://www.nsi.dk/hsuid/2016/08/hsuid-1.1.xsd" xmlns:ns2="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" xmlns:ns3="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0" xmlns:ns4="urn:ihe:iti:xds-b:2007" xmlns:ns5="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns:ns6="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:ns7="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns8="http://www.w3.org/2000/09/xmldsig#" xmlns:ns9="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
         <ns2:RegistryErrorList highestSeverity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Warning">
            <ns2:RegistryError codeContext="BUSINESS_RULE|||Hvis en kontakt er af typen &quot;diagnoseindberetning&quot;, skal kontaktens sluttidspunkt være lig med starttidspunktet plus ét minut, og prioritet skal være i kodelisten admin.prioritet.plan" errorCode="InvalidDocumentContent" location="C1DEE9F6-EF9D-452D-A4B3-EC358F550826^7cb8dde4-8a2b-43f4-978b-0c92c7b2023f|||//*[child::*[local-name()='id' and @root='C1DEE9F6-EF9D-452D-A4B3-EC358F550826' and @extension='a801fbbe-1e90-4a25-b076-2a49a1e1af88']]|||sds:lpr:3.0.4|||05.107" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Warning"/>
            <ns2:RegistryError codeContext="BUSINESS_RULE|||Henvisningsårsagen skal findes i en af kodelisterne diag, proc.act, proc.opr, proc.und" errorCode="InvalidDocumentContent" location="C1DEE9F6-EF9D-452D-A4B3-EC358F550826^7cb8dde4-8a2b-43f4-978b-0c92c7b2023f|||//*[child::*[local-name()='id' and @root='C1DEE9F6-EF9D-452D-A4B3-EC358F550826' and @extension='a6750254-6557-476f-b038-06b5d6d0b2e1']]|||sds:lpr:3.0.4|||06.a" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Warning"/>
            <ns2:RegistryError codeContext="BUSINESS_RULE|||Et afsluttet forløbselement skal have en afslutningsmåde" errorCode="InvalidDocumentContent" location="C1DEE9F6-EF9D-452D-A4B3-EC358F550826^7cb8dde4-8a2b-43f4-978b-0c92c7b2023f|||//*[child::*[local-name()='id' and @root='C1DEE9F6-EF9D-452D-A4B3-EC358F550826' and @extension='a6750254-6557-476f-b038-06b5d6d0b2e1']]|||sds:lpr:3.0.4|||02.02" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Warning"/>
            <ns2:RegistryError codeContext="BUSINESS_RULE|||Hvis et forløbselement er afsluttet, så skal kontakter knyttet til forløbselementet også være afsluttet med et sluttidspunkt, der ligger før eller samtidig med forløbselementets sluttidspunkt" errorCode="InvalidDocumentContent" location="C1DEE9F6-EF9D-452D-A4B3-EC358F550826^7cb8dde4-8a2b-43f4-978b-0c92c7b2023f|||//*[child::*[local-name()='id' and @root='C1DEE9F6-EF9D-452D-A4B3-EC358F550826' and @extension='a801fbbe-1e90-4a25-b076-2a49a1e1af88']]|||sds:lpr:3.0.4|||05.31" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Warning"/>
            <ns2:RegistryError codeContext="BUSINESS_RULE|||En kontakts periode skal ligge inden for forløbselementets periode" errorCode="InvalidDocumentContent" location="C1DEE9F6-EF9D-452D-A4B3-EC358F550826^7cb8dde4-8a2b-43f4-978b-0c92c7b2023f|||//*[child::*[local-name()='id' and @root='C1DEE9F6-EF9D-452D-A4B3-EC358F550826' and @extension='a801fbbe-1e90-4a25-b076-2a49a1e1af88']]|||sds:lpr:3.0.4|||05.24" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Warning"/>
            <ns2:RegistryError codeContext="BUSINESS_RULE|||Hvis en kontakt er afsluttet, skal der være tilknyttet én aktionsdiagnose" errorCode="InvalidDocumentContent" location="C1DEE9F6-EF9D-452D-A4B3-EC358F550826^7cb8dde4-8a2b-43f4-978b-0c92c7b2023f|||//*[child::*[local-name()='id' and @root='C1DEE9F6-EF9D-452D-A4B3-EC358F550826' and @extension='a801fbbe-1e90-4a25-b076-2a49a1e1af88']]|||sds:lpr:3.0.4|||05.14" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Warning"/>
            <ns2:RegistryError codeContext="BUSINESS_RULE|||To opholdsadresser til samme kontakt, der følger hinanden, skal afløse hinanden uden tidsoverlap eller -slip" errorCode="InvalidDocumentContent" location="C1DEE9F6-EF9D-452D-A4B3-EC358F550826^7cb8dde4-8a2b-43f4-978b-0c92c7b2023f|||//*[child::*[local-name()='id' and @root='C1DEE9F6-EF9D-452D-A4B3-EC358F550826' and @extension='a801fbbe-1e90-4a25-b076-2a49a1e1af88']]|||sds:lpr:3.0.4|||09.02" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Warning"/>
            <ns2:RegistryError codeContext="BUSINESS_RULE|||En kontakts periode skal ligge inden for forløbselementets periode" errorCode="InvalidDocumentContent" location="C1DEE9F6-EF9D-452D-A4B3-EC358F550826^7cb8dde4-8a2b-43f4-978b-0c92c7b2023f|||//*[child::*[local-name()='id' and @root='C1DEE9F6-EF9D-452D-A4B3-EC358F550826' and @extension='a801fbbe-1e90-4a25-b076-2a49a1e1af88']]|||sds:lpr:3.0.4|||05.22" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Warning"/>
            <ns2:RegistryError codeContext="BUSINESS_RULE|||Hvis kontakten ikke er af typen &quot;fysisk fremmøde&quot;, må der ikke registreres opholdsadresse på kontakten" errorCode="InvalidDocumentContent" location="C1DEE9F6-EF9D-452D-A4B3-EC358F550826^7cb8dde4-8a2b-43f4-978b-0c92c7b2023f|||//*[child::*[local-name()='id' and @root='C1DEE9F6-EF9D-452D-A4B3-EC358F550826' and @extension='a801fbbe-1e90-4a25-b076-2a49a1e1af88']]|||sds:lpr:3.0.4|||05.106" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Warning"/>
         </ns2:RegistryErrorList>
      </ns2:RegistryResponse>
   </soap:Body>
</soap:Envelope>
```

I have attached the CDA document here:
[cda-create-fixed.zip](https://github.com/scandihealth/lpr3-docs/files/1899032/cda-create-fixed.zip)

Patient CPR: 1010101010
ForløbsId: a6750254-6557-476f-b038-06b5d6d0b2e1

**Comment by jonigkeit** [comment]
A heads-up: your episode of care extension is not a UUIDv**5**. This will eventually fail.

**Comment by jonigkeit** [comment]
We can reproduce the issue and have a fix for it in place. Expect this issue resolved with the next deployed release.
Thank you for the very useful information provided in this issue.

**Comment by RasmusThernoe** [comment]
I have tried to delete an Encounter using correct UUIDv5 and I get:

```xml
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
   <soap:Header>
      <ns10:Header xmlns="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:ns10="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd" xmlns:ns11="http://www.nsi.dk/hsuid/2016/08/hsuid-1.1.xsd" xmlns:ns2="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" xmlns:ns3="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0" xmlns:ns4="urn:ihe:iti:xds-b:2007" xmlns:ns5="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns:ns6="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:ns7="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns8="http://www.w3.org/2000/09/xmldsig#" xmlns:ns9="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
         <ns10:SecurityLevel>3</ns10:SecurityLevel>
         <ns10:Linking>
            <ns10:MessageID>d7f374e7c0a8380100c79bd5a367ebf2</ns10:MessageID>
         </ns10:Linking>
         <ns10:FlowStatus>flow_finalized_succesfully</ns10:FlowStatus>
      </ns10:Header>
   </soap:Header>
   <soap:Body>
      <ns2:RegistryResponse status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Success" xmlns="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:ns10="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd" xmlns:ns11="http://www.nsi.dk/hsuid/2016/08/hsuid-1.1.xsd" xmlns:ns2="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" xmlns:ns3="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0" xmlns:ns4="urn:ihe:iti:xds-b:2007" xmlns:ns5="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns:ns6="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:ns7="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns8="http://www.w3.org/2000/09/xmldsig#" xmlns:ns9="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
         <ns2:RegistryErrorList highestSeverity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Warning">
            <ns2:RegistryError codeContext="BUSINESS_RULE|||Kontaktens prioritet skal findes i kodelisten admin.prioritet" errorCode="InvalidDocumentContent" location="072CB92B-0A45-58F6-9703-8E6B7CAB935E^63916526-f2c0-57de-939d-ffbb6d3f9642|||//*[child::*[local-name()='id' and @root='072CB92B-0A45-58F6-9703-8E6B7CAB935E' and @extension='0df9b164-5739-5e28-b710-3716dc69d416']]|||sds:lpr:3.0.4|||05.b" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Warning"/>
            <ns2:RegistryError codeContext="BUSINESS_RULE|||En kontakts periode skal ligge inden for forløbselementets periode." errorCode="InvalidDocumentContent" location="072CB92B-0A45-58F6-9703-8E6B7CAB935E^63916526-f2c0-57de-939d-ffbb6d3f9642|||//*[child::*[local-name()='id' and @root='072CB92B-0A45-58F6-9703-8E6B7CAB935E' and @extension='0df9b164-5739-5e28-b710-3716dc69d416']]|||sds:lpr:3.0.4|||05.21" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Warning"/>
            <ns2:RegistryError codeContext="BUSINESS_RULE|||To opholdsadresser til samme kontakt, der følger hinanden, skal afløse hinanden uden tidsoverlap eller -slip" errorCode="InvalidDocumentContent" location="072CB92B-0A45-58F6-9703-8E6B7CAB935E^63916526-f2c0-57de-939d-ffbb6d3f9642|||//*[child::*[local-name()='id' and @root='072CB92B-0A45-58F6-9703-8E6B7CAB935E' and @extension='0df9b164-5739-5e28-b710-3716dc69d416']]|||sds:lpr:3.0.4|||09.02" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Warning"/>
         </ns2:RegistryErrorList>
      </ns2:RegistryResponse>
   </soap:Body>
</soap:Envelope>
```

The Encounter is still not removed or marked as nullified in [https://lpradm-test.sds.dsdn.dk/gui-client/LPR.html](url).

I have attached the CDA document here:
[TC7-Encounter-Delete.zip](https://github.com/scandihealth/lpr3-docs/files/1923595/TC7-Encounter-Delete.zip)

When is next deployed release?

**Comment by jonigkeit** [comment]
**RESOLUTION**
A side effect of [JSR 338](http://download.oracle.com/otn-pub/jcp/persistence-2_2-mrel-spec/JavaPersistence.pdf) - section 3.2.2 caused removed entities to be managed again.
>* For all entities Y referenced by a relationship from X, if the relationship to Y has been annotated with the cascade element value cascade=PERSIST or cascade=ALL, the persist operation is applied to Y
>* If X is a removed entity, it becomes managed.
